### PR TITLE
General Cleanup

### LINKED ISSUE #54: General cleanup
Some general cleanup needs to be done in a maintenance branch:

- There is some overlap with object methods. Let's make a base object and have them inherit these methods maybe.
- Defaults need to be set when re-assigning chores (it should show the current assignee in the dropdown, like I have already done on the chore_edit screen)
- Consistent unique titles need to be added for each route.
- Other misc cleanup.

### PR DESCRIPTION
**Pull request by jboyer87**
Fixes #54 . Adds a base object to inherit from for our models, fixes some inconsistencies, fixes titles, fixes the chore reassign page.

### CODE REVIEW

**Comment by arc2nd** [comment]
I'm getting the following error trying to login to this one:

ProgrammingError: (psycopg2.ProgrammingError) column chores.recurrence_id does not exist
LINE 1: ...hores_points, chores.complete AS chores_complete, chores.rec...
                                                             ^
HINT:  Perhaps you meant to reference the column "chores.recurrence".
 [SQL: 'SELECT chores.id AS chores_id, chores.assigned_to AS chores_assigned_to, chores.due_date AS chores_due_date, chores.name AS chores_name, chores.description AS chores_description, chores.points AS chores_points, chores.complete AS chores_complete, chores.recurrence_id AS chores_recurrence_id \nFROM chores'] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by jboyer87** [comment]
Did you run the DB scripts before?

**Comment by arc2nd** [comment]
Yes, I had run the DB scripts before. I'll try again.

**Comment by arc2nd** [comment]
huh, rerunning them seems to have fixed it.

**Pull request merged**
